# Database configuration for gateway component

- name: Create Gateway database
  mysql_db:
    name: "{{ database_gateway_name }}"
    state: present
    login_host: "{{ database_lb_address }}"
    login_user: "{{ database_stepup_deploy_user }}"
    login_password: "{{ database_stepup_deploy_password | vault(vault_keydir) }}"

- name: Create gateway user
  mysql_user:
    name: "{{ database_gateway_user }}"
    host: "%"
    password: "{{ database_gateway_password | vault(vault_keydir) }}"
    priv: "{{ database_gateway_name }}.*:SELECT"
    login_host: "{{ database_lb_address }}"
    login_user: "{{ database_stepup_deploy_user }}"
    login_password: "{{ database_stepup_deploy_password | vault(vault_keydir) }}"

- name: Create gateway read-only user
  mysql_user:
    name: "{{ database_gateway_readonly_user }}"
    host: "%"
    password: "{{ database_gateway_readonly_password | vault(vault_keydir) }}"
    priv: "{{ database_gateway_name }}.*:SELECT"
    login_host: "{{ database_lb_address }}"
    login_user: "{{ database_stepup_deploy_user }}"
    login_password: "{{ database_stepup_deploy_password | vault(vault_keydir) }}"
  when: database_gateway_readonly_user is defined
