# Database configuration for u2f component

- name: Create u2f database
  mysql_db:
    name: "{{ database_u2f_name }}"
    state: present
    login_host: "{{ database_lb_address }}"
    login_user: "{{ database_stepup_deploy_user }}"
    login_password: "{{ database_stepup_deploy_password | vault(vault_keydir) }}"

- name: Create gateway deploy user with ALL access to u2f database
  mysql_user:
    name: "{{ database_gateway_deploy_user }}"
    host: "%"
    password: "{{ database_gateway_deploy_password | vault(vault_keydir) }}"
    priv: "{{ database_u2f_name }}.*:ALL\ PRIVILEGES,GRANT"
    login_host: "{{ database_lb_address }}"
    login_user: "{{ database_stepup_deploy_user }}"
    login_password: "{{ database_stepup_deploy_password | vault(vault_keydir) }}"

- name: Create DB user for u2f component
  mysql_user:
    name: "{{ database_u2f_user }}"
    host: "%"
    password: "{{ database_u2f_password | vault(vault_keydir) }}"
    priv: "{{ database_u2f_name }}.*:SELECT,INSERT,DELETE,UPDATE"
    login_host: "{{ database_lb_address }}"
    login_user: "{{ database_stepup_deploy_user }}"
    login_password: "{{ database_stepup_deploy_password | vault(vault_keydir) }}"

